# Configuration SonarQube - Project ReviewMe

# Project identification
sonar.projectKey=reviewme-core
sonar.projectName=ReviewMe
sonar.projectVersion=1.0

# Path to sources
sonar.sources=app,resources/views,routes
sonar.tests=tests

# Language specific configuration
sonar.php.coverage.reportPaths=clover.xml
sonar.php.tests.reportPath=junit.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions - Global
sonar.exclusions=vendor/**,node_modules/**,storage/**,public/build/**,database/migrations/**

# Exclusions - Test Files from Source Analysis
sonar.test.inclusions=tests/**/*.php
